url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "https://kwik-insure.netlify.app" # the subpath of your site, e.g. /blog
title: "" # the name of your site, e.g. ACME Corp.

# Open Graph Specific Tags
open-graph:
  type: ""
  image: ""

twitter:
  type: "" #The card type, which will be one of “summary”, “summary_large_image”, “app”, or “player”.
  id: "2582378478"

  
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# fontawesome: "https://kit.fontawesome.com/9eb6b1689c.js"

# material-icon: "https://fonts.googleapis.com/icon?family=Material+Icons"

google-font: https://fonts.googleapis.com/css2?family=Work+Sans:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"

# isPWA: true

# swup-animation: "https://unpkg.com/swup@latest/dist/swup.min.js"

sass:
  style: compressed # possible values: nested expanded compact compressed

stylesheet: # place external url here

collections:
  vehicles:
    output: true
    permalink: /product/vehicle/marketplace/:path/